server:
  port: 8080
  servlet:
    contextPath: /eltropy/bank
spring:
  application:
    name: ELTROPY-BANK-SOLUTIONS
users:
  servicename: ELTROPY-BANK-USERS-SERVICE
accounts:
  servicename: ELTROPY-BANK-ACCOUNT-SERVICE